everyleaf/hotwire_ja

README.md

[いただいたPR](https://github.com/everyleaf/hotwire_ja/pull/34#discussion_r1436188865)が、原文を`<details>`で残すスタイルでした。このスタイルだと読者も訳文と見比べやすくとても良いと感じたため、以降のPRを同スタイルに合わせます。
[作業ガイド](https://github.com/everyleaf/hotwire_ja/README.md)の手順3にて、レビューが終わるまでは原文を残しておいてほしいという記載がありますがこれが上記方針と相反するため、手順3を書き換える形でガイドに記載します。

原文をdetailsで残して貰う形に変更

---

turbo/reference/events.md

元記事：https://turbo.hotwired.dev/reference/events
元記事コミット：　記録してなかったのでわかんないです（次から記録する）　多分この辺より後ではなさそう... https://github.com/hotwired/turbo-site/commit/c4ee2fd4150e43cb5f33758ab7e7c267c5eedc3b
https://github.com/everyleaf/hotwire_ja/issues/26

Turboリファレンスのイベントの章を翻訳

---

layouts/base.html

英語ページのタイトルに合わせて、標題の通り修正してみました! 📝 ✅ 
```html
<title>Turbo Handbook</title>
```
cf. https://turbo.hotwired.dev/handbook/introduction

正式なタイトル名に修正: TurboHandbook -> Turbo Handbook

---

README.md

今まではハードコーディングでサイドバーを生成していましたが、今後はcollectionsの機能を利用するためページの並び順を固定する必要があります。
本家同様、Front Matterにorderプロパティを追加してそれを基準にソートする方法が便利なのでそれを踏襲する実装にしました。（基本的には本家と同じ並び順で良いので翻訳ページを作るときにそのまま残していただきたい）
ついては、READMEにorderについての記載がなかったのでそれを追記しました。

今後はFront Matterの order を利用するので残してもらう

---

.github/dependabot.yml

GitHub Actions で Node.js に関するワーニングが出ていた
- https://github.com/everyleaf/hotwire_ja/actions/runs/8242241024
GtiHub Actions のバージョンを定期的にあげることで、内部で利用されている Node.js などのバージョンもあげる仕組みを作る

Dependabot を利用して、GitHub Actions のバージョンを週毎に確認する

---

_includes/section-nav.html
turbo/handbook/page_refreshes.md

元siteコミットハッシュ：[commit 0b2c287083c91402d44fd3075cc66bc1d8d8ee6e](https://github.com/hotwired/turbo-site/commit/0b2c287083c91402d44fd3075cc66bc1d8d8ee6e)
-  Turboハンドブックにページリフレッシュの章を追加（元サイトへの追従）
- リンクを追加

Handbook 03 page refreshes

---

turbo/handbook/frames.md

frames.md の Front Matterにorderの指定が重複していたため、[buildが失敗している](https://github.com/everyleaf/hotwire_ja/actions/runs/10362147207)。これを直したい
- frames.mdの正しい順序は `order:4` ([本家](https://github.com/hotwired/turbo-site/blob/main/_source/handbook/04_frames.md))

[turbo handbook] framesのページの並び順が重複していた

---

index.md
turbo/handbook/introduction.md

わかりやすい翻訳資料を作成くださりありがとうございますmm
助詞が抜けている文章を見つけたので、修正しています。
```diff
Turboストリーム: Deliver live page changes
非同期なアクションに応答してページの一部を変化させることで、アプリケーションをとても
- 生き生きしたものできます。
+ 生き生きしたものにできます。
```
(該当箇所付近: [アプリケーションをとても生き生きしたものできます。](https://everyleaf.github.io/hotwire_ja/#turbo%E3%82%B9%E3%83%88%E3%83%AA%E3%83%BC%E3%83%A0%3A-deliver-live-page-changes))

文中に助詞が抜けていたため、助詞を追加しました。

---

.eleventy.js

Issue
A deprecated warning is raised because the currently specified option is outdated.
```console
% npm run serve
...
Warning: Using deprecated markdown-it-anchor permalink option, see https://github.com/valeriangalliat/markdown-it-anchor#permalinks
...
```
Solution
Update the markdown-it-anchor permalink option to use the current configuration.
ref: https://github.com/valeriangalliat/markdown-it-anchor#permalinks

Remove a deprecated warning about markdown-it-anchor permalink option

---

.eleventy.js
package-lock.json
package.json

ref: https://github.com/everyleaf/hotwire_ja/pull/92
Eleventy v3.0.0 fully supports ESM.
- ref: https://github.com/11ty/eleventy/releases/tag/v3.0.0
Additionally, using `require("@11ty/eleventy")` with Eleventy v3.0.0 results
in compatibility issues as follows. Therefore, this is an appropriate time to
migrate our configuration from CommonJS to ESM.
```
> hotwire_ja@1.0.0 build:11ty
> eleventy --pathprefix=hotwire_ja
[11ty] Eleventy Error (CLI):
[11ty] 1. Error in your Eleventy config file '.eleventy.js'. (via EleventyConfigError)
[11ty] 2. `require("@11ty/eleventy")` is incompatible with Eleventy v3 and this version of Node. You have a few options:
[11ty]    1. (Easiest) Change the `require` to use a dynamic import inside of an asynchronous CommonJS configuration
[11ty]       callback, …
```

Upgrade Eleventy from 2 to 3

---

_assets/css/base/_elements.scss
_assets/css/components/_anchor.scss
_assets/css/components/_button.scss
_assets/css/components/_docs.scss
_assets/css/components/_grid.scss
_assets/css/components/_jump.scss
_assets/css/components/_landing.scss
_assets/css/components/_nav.scss
_assets/css/components/_page.scss
_assets/css/main.scss

There are some warning when we run `npm run serve` as follows. Because using `@import` rules is depreacated now.
```console
$ npm run serve
Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
More info and automated migrator: https://sass-lang.com/d/import
╷
2 │ @import "base/mixins",
│         ^^^^^^^^^^^^^
╵
_assets/css/main.scss 2:9  root stylesheet
Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
More info and automated migrator: https://sass-lang.com/d/import
```
We can use Sass migrator which is provided by Sass project. This migrator automatically update your stylesheets to use the module system. It will resove the above warnings.
```console
$ npm install -g sass-migrator
$ sass-migrator module …
```

Use sass-migrator to update our stylesheets without `@import` rules

---

layouts/base.html

#104 の対応
ページのタイトルを前、`section_title`のまとまりごとのタイトルを後となるように変更した

タイトルの並び順の変更

---

turbo/handbook/native.md

We refer to the order in https://github.com/hotwired/turbo-site/tree/main/_source/handbook.

turbo handbook: fix duplicated order

---

layouts/base.html

#106 　対応
- ISSUEにある「Hotwireリファレンス」だと階層的に微妙だったので「Hotwire ドキュメント」を採用
- リンクがないのも押した時のユーザー体験としてどうかと思うので、現在のTOPであるTurbo に飛ばしている

jumplistの文言変更&トップへのリンクを本家に飛ばさないようにした

---

turbo/reference/reference.json

#121 の対応
`section_title`の「ハンドブック」を「Turbo リファレンス: Hotwire ドキュメント（有志翻訳版）」 に変更した

タイトルの「リファレンス」を「Turbo リファレンス: Hotwire ドキュメント（有志翻訳版）」に変更

---

turbo/handbook/handbook.json

#105 の対応
`section_title`の「ハンドブック」を「Turbo ハンドブック: Hotwire ドキュメント（有志翻訳版）」 に変更した

タイトルの「ハンドブック」を「Turbo ハンドブック: Hotwire ドキュメント（有志翻訳版）」 に変更

---

layouts/base.html

#108 の対応の一環で、Googleアナリティクスで使用するトラッキングコードの追加を追加しました。

Googleアナリティクスで使用するトラッキングコードの追加

---

Rakefile
tasks/diff_task.rb
tasks/source_file.rb
tasks/translated_file.rb
tasks/translation_pr.rb

GitHub: GH-130
今回の変更では、翻訳元である`hotwired/turbo-site`との差分を自動検出し、内容を差分として PR に反映する仕組みを実装しました。これにより、翻訳者は翻訳対象ファイルの変更点を確認するだけで済み、手動でのコミットハッシュ比較や差分検出作業が不要となります。
- **対象ファイルの収集**: [532b914](https://github.com/everyleaf/hotwire_ja/pull/131/commits/532b914338e867fd0ca4f4bc4662161917a4cc72): 翻訳元のソースファイルと翻訳ファイルを収集します。
- **差分検出機能の追加**: [fd8b692](https://github.com/everyleaf/hotwire_ja/pull/131/commits/fd8b692e546056a4c3e1935e3fb6d5fae05b42ad) : ソースファイルと翻訳ファイルの対応付けを行い、差分が存在する場合は翻訳元の最新のコミットハッシュと翻訳ファイル内の共に差分内容を取得します。
- **PR作成処理の自動化**: [2adb52d](https://github.com/everyleaf/hotwire_ja/pull/131/commits/2adb52d40d8ff55ab19e2a06771f4298d808d77f): 差分内容を含むPRを作成します。（または既存PRが存在する場合は内容を更新します。）
<details>
<summary>大まかなフローチャート</summary>
```mermaid
flowchart TD
A[Start: rake translate:diff] --> B[Collect Source Files] …
```

Add Rake Task for automatic translation diff detection

---

.github/workflows/translation-diff-monitor.yml

GitHub: GH-130
This PR introduces a new CI workflow that automatically executes the Rake task for updating translations on a daily basis.

ci translation-diff-monitor: automatically update translations daily

---

.gitignore
Gemfile

The following error happened because we forgot to add Gemfile at GH-135.
```
bundle
shell: /usr/bin/bash -e {0}
env:
TURBO_SITE_REPOSITORY: /home/runner/work/hotwire_ja/hotwire_ja/turbo-site
Could not locate Gemfile
Error: Process completed with exit code 10.
```

ci translation-diff-monitor: add missing Gemfile

---

tasks/diff_task.rb
tasks/translated_file.rb
tasks/translation_pr.rb

These changes help avoid generating unnecessary diffs and prevent workflow interruptions.
- Skip processing when the diff content is empty.
- Skip updating the commit value in translated files if it has not changed.
- Handle the case where `gh pr view` fails due to no existing PR without throwing an error.
- Switch back to the main branch after creating or updating a PR.
- Change the base branch for the PR from auto-translations-update to main because auto-translations-update was the debug branch.

fix: automatic translation diff detection 

---

tasks/translation_pr.rb

GitHub: GH-130
This change includes GitHub compare URL in translation PR description as a reference.

ci translation-diff-monitor: add diff url

---

turbo/handbook/drive.md

- #175 の差分の更新対応
- 現在最新の79760f0まで
- 原文に見出しの追加
- 原文内に見出しへのリンクが埋め込まれている部分があったため、原文にも見出しが記載されていた方が親切かと思ったので追加した

turbo handbook drive: updated translation

---

turbo/reference/attributes.md

GitHub: fix GH-179
日本語訳マニュアルをいつも便利に使わさせて頂いてます！
`turbo-prefetch` の説明がなかったので追加しました。
プリフェッチを無効にしたくて、マニュアルを読んでいると `turbo-preload` しか載っていなくて、でも `turbo-preload="false"` とコードに書いても効果がなく、原文を調べてみてやっと `turbo-prefetch="false"` が正解であることがわかったため。

turbo reference attributes: update translations
